[modules]
[modules.preprocessor]
name = "com.scalar.db.benchmarks.ycsb.MultiStorageLoader"
path = "./build/libs/scalardb-benchmarks-all.jar"
[modules.processor]
name = "com.scalar.db.benchmarks.ycsb.MultiStorageWorkloadF"
path = "./build/libs/scalardb-benchmarks-all.jar"
[modules.postprocessor]
name = "com.scalar.db.benchmarks.ycsb.YcsbReporter"
path = "./build/libs/scalardb-benchmarks-all.jar"

[common]
concurrency = 4
run_for_sec = 5
ramp_for_sec = 5

[stats]
realtime_report_enabled = true

[ycsb_config]
ops_per_tx = 1
record_count = 1000
load_concurrency = 4
#load_batch_size = 10
#load_overwrite = true

[database_config]
config_file = "/path/to/multi-storage-scalardb.properties"
