[modules]
[modules.preprocessor]
name = "com.scalar.db.benchmarks.ycsb.Loader"
path = "./build/libs/scalardb-benchmarks-all.jar"
[modules.processor]
name = "com.scalar.db.benchmarks.ycsb.WorkloadF"
path = "./build/libs/scalardb-benchmarks-all.jar"
[modules.postprocessor]
name = "com.scalar.db.benchmarks.ycsb.YcsbReporter"
path = "./build/libs/scalardb-benchmarks-all.jar"

[common]
concurrency = 1
run_for_sec = 1
ramp_for_sec = 1

[stats]
realtime_report_enabled = true

[ycsb_config]
record_count = 1
records_per_partition = 100
payload_size = 1000
ops_per_tx = 1
load_concurrency = 1

[database_config]
config_file = "./client.properties"
